### PR TITLE
Remove obsolete hacks in build.sh

### PR DESCRIPTION
**Pull request by startergo**

### CODE REVIEW

**Review by xaionaro — APPROVED** [review]
Let's merge it if it will pass auto-tests.

**Comment by xaionaro** [comment]
@startergo : Hey. I added you to collaborators of this project. If you could accept the invite and push this change to a new branch in **this** repository, and re-create the Pull Request (from this new branch), I hope the auto-tests will execute. Let me know if this is not convenient for you -- I'll try to find another solution.

Screenshot from 2022-11-24 00-00-14

**Comment by startergo** [comment]
image
This fails on my branch.

**Comment by xaionaro** [comment]
> @startergo : Hey. I added you to collaborators of this project. If you could accept the invite and push this change to a new branch in **this** repository, and re-create the Pull Request (from this new branch), I hope the auto-tests will execute. Let me know if this is not convenient for you -- I'll try to find another solution.

OK, I did it myself. https://github.com/xaionaro/edk2-builder-docker/pull/28

**Comment by xaionaro** [comment]
> > @startergo : Hey. I added you to collaborators of this project. If you could accept the invite and push this change to a new branch in **this** repository, and re-create the Pull Request (from this new branch), I hope the auto-tests will execute. Let me know if this is not convenient for you -- I'll try to find another solution.
> 
> OK, I did it myself. #28

It helped. Merging :)

**Comment by xaionaro** [comment]
@startergo : Could you review https://github.com/xaionaro/edk2-builder-docker/pull/29 please?

**Pull request merged**
